name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  test_build_push:
    name: Test and Build & Push Docker image

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: michaelwoods/onstar2mqtt
          tags: michaelwoods/onstar2mqtt:latest
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
